{{--
  Template Name: Terms and Conditions
--}}

@extends('layouts.app')

@section('content') 
  @while(have_posts()) @php(the_post())
    @include('partials.page-header')
          <article @php(post_class())>
  <header>
    <h4 class="entry-title">DIGITIENDAS MARESI, S.A.P.I. DE C.V<br>
    <b>TÉRMINOS Y CONDICIONES</b>
    </h4>
  </header>
  <div class="entry-summary">
    <b>Por favor, lee atentamente estos términos y condiciones antes de usar esta web.</b>
<p>DIGITIENDAS MARESI, S.A.P.I. DE C.V. (en adelante BAMBINI.CLUB), con domicilio en Tijuana, Baja California, México, Inscrita en el Registro Público de Comercio de Tijuana, Baja California, es la propietaria del sitio web www.bambini.club, que tiene por objeto la venta de todo tipo de productos para bebés. </p>
<p>Los presentes términos y condiciones tienen como objeto regular las transacciones comerciales que surjan entre www.bambini.club y sus usuarios. Tanto la navegación por la tienda online como la adquisición de cualquiera de los productos ofertados en ella suponen la aceptación como usuario, sin reservas de ninguna clase, de todas y cada una de los presentes términos y condiciones de contratación y utilización. El sitio web www.bambini.club podrá, en todo momento, y sin previo aviso, modificar los presentes términos y condiciones.
Productos, Contenido y Especificaciones: Todas las características, contenido, especificaciones, productos y precios de los productos y servicios descritos o detallados en www.bambini.club están sujetos a cambios sin previo aviso. </p>
<p>Cualquier peso, medida o descripción similar se indica por aproximación y su mención tiene el único propósito de dar información. BAMBINI.CLUB, que opera esta Web, realiza todos los esfuerzos posibles para mostrar con la mayor exactitud posible las características de sus productos, incluyendo los colores aplicables; sin embargo, el color real siempre dependerá del sistema del Usuario y no podemos garantizar que ese sistema enseñe los colores exactos. La inclusión de cualquier producto o servicio en esta Web, no implica ni garantiza que tales productos o servicios estén disponibles en cualquier momento. BAMBINI.CLUB no se hace responsable del incumplimiento de las leyes que sus clientes puedan hacer (incluyendo los requisitos de edad mínima) con respecto a la posesión, uso y venta de cualquier producto comprado en esta Web. Por el hecho de realizar un pedido, el Usuario acepta que el/los producto/s comprado/s solo se usarán de manera legal. La compra de cualquier CD, DVD y productos similares implica el uso privado de los mismos, en domicilio privado (donde no se cobra por entrar), en actuaciones no públicas y sin que puedan ser duplicados ni copiados.</p>
<p><b>Uso de esta Web:</b> Todos los contenidos de la Web, tales como textos, gráficos, fotografías, logotipos, iconos, imágenes, así como el diseño gráfico, código fuente y software, son de la exclusiva propiedad de BAMBINI.CLUB o de terceros, cuyos derechos al respecto ostenta legítimamente BAMBINI.CLUB, estando por lo tanto protegidos por la legislación nacional e internacional. Queda estrictamente prohibido la utilización de todos los elementos objeto de propiedad industrial e intelectual con fines comerciales así como su distribución, modificación, alteración o descompilación.</p>
<p><b>Marcas Registradas:</b> Ciertas marcas registradas, nombres comerciales, marcas de servicio y logos usados o mostrados en esta Web están registrados a nombre de BAMBINI.CLUB, proveedores o sus asociados como tal. Por otro lado, ciertas marcas registradas, nombres comerciales y marcas de servicio usados o mostrados en esta Web están registrados a nombre de sus respectivos titulares.</p>
<p><b>Links a esta Web:</b> Queda expresamente prohibida la introducción de hipervínculos con fines comerciales en páginas web ajenas a www.bambini.club, que permitan el acceso a nuestra Web, sin consentimiento previo. En todo caso, la existencia de hipervínculos en sitios web ajenos a nosotros, no implicará en ningún caso la existencia de relaciones comerciales o mercantiles con el titular de la página web donde se establezca el hipervínculo, ni la aceptación por parte de www.bambini.club de sus contenidos o servicios.</p>
<p><b>Links de Terceras Partes:</b> www.bambini.club no garantiza, ni asume ningún tipo de responsabilidad por los daños y perjuicios sufridos por el acceso a Servicios de terceros a través de conexiones, vínculos o links de los sitios enlazados ni sobre la exactitud o fiabilidad de los mismos. La función de los enlaces que aparecen en www.bambini.club es exclusivamente la de informar al usuario sobre la existencia de otras fuentes de información en Internet, donde podrá ampliar los Servicios ofrecidos por la Web. El sitio web www.bambini.club no será, en ningún caso responsable del resultado obtenido a través de dichos enlaces o de las consecuencias que se deriven del acceso por los usuarios a los mismos. Estos Servicios de terceros son proporcionados exclusivamente por éste, por lo que www.bambini.club no puede controlar y no controla la licitud ni la calidad de los Servicios. En consecuencia, el usuario debe extremar la prudencia en la valoración y utilización de la información y servicios existentes en los contenidos de terceros.</p>
<p><b>Material inadecuado:</b> Con carácter general, el Usuario se obliga al cumplimiento de los presentes términos y condiciones, así como a cumplir las advertencias o instrucciones específicas de uso contenidas en las mismas o en la web y a obrar siempre conforme a la Ley, a las buenas costumbres y a las exigencias de la buena fe, empleando la diligencia adecuada a la naturaleza del servicio del que disfruta, absteniéndose de utilizar la Web de cualquier forma que pueda impedir, dañar o deteriorar el normal funcionamiento de los mismos y/o los bienes o derechos de www.bambini.club. </p>
<p>Concretamente, y sin que ello implique restricción alguna a la obligación asumida por el Usuario con carácter general de conformidad con el apartado anterior, el Usuario se obliga, en la utilización de la web, así como en la prestación de los servicios a: (I) En el caso de registrarse, a proporcionar verazmente sus datos y a mantenerlos actualizados; (II) No introducir, almacenar o difundir en o desde la web, cualquier información o material que fuera difamatorio, injurioso, obsceno, amenazador, xenófobo, incite a la violencia a la discriminación por razón de raza, sexo, ideología, religión o que de cualquier forma atente contra la moral, el orden público, los derechos fundamentales, las libertades públicas, el honor, la intimidad o la imagen de terceros y en general la normativa vigente; (III) No introducir, almacenar o difundir a través o mediante la Web ningún programa de ordenador, datos, virus, código, equipo de hardware o de telecomunicaciones o cualquier otro instrumento o dispositivo electrónico o físico que sea susceptible de causar daños en la Web, en cualquiera de los Servicios, o en cualquiera de los equipos, sistemas de www.bambini.club, de cualquier Usuario, de los proveedores de www.bambini.club o en general de cualquier tercero, o que de cualquier otra forma sea capaz de causarles cualquier tipo de alteración o impedir el normal funcionamiento de los mismos; (IV) No realizar actividades publicitarias, promocionales o de explotación comercial a través de la Web, no utilizando los contenidos y en particular la información obtenida a través de la Web para remitir publicidad, enviar mensajes con fines de venta directa o con cualquier otro fin comercial, ni para recoger o almacenar datos personales de terceros; (V) No utilizar identidades falsas, ni suplantar la identidad de otros en la utilización de la Web o en la utilización de cualquiera de los servicios de la Web, incluyendo la utilización en su caso de contraseñas o claves de acceso de terceros o de cualquier otra forma; (VI) No destruir, alterar, utilizar para su uso, inutilizar o dañar los datos, informaciones, programas o documentos electrónicos de www.bambini.club, sus proveedores o terceros; (VII) No introducir, almacenar o difundir mediante la web cualquier contenido que infrinja derechos de propiedad intelectual, industrial o secretos empresariales de terceros, ni en general ningún contenido del cual no ostentara, de conformidad con la ley, el derecho a ponerlo a disposición de tercero.</p>
<p><b>Información al Usuario:</b> Con excepción de la información personal, que estará sujeta a la Política de Privacidad por la que se rige esta Web, cualquier material, información, sugerencia, idea, concepto, know-how, técnica, cuestión, comentario u otro tipo de comunicación que pueden ser enviados desde o a través de esta Web, de cualquier manera (“Comunicaciones del Usuario”), es y será considerada como no confidencial y sin derechos de propiedad intelectual. Nosotros, nuestros asociados y nuestros representantes podremos usar cualquiera o todas las Comunicaciones del Usuario para cualquier fin incluyendo, sin limitación alguna, la reproducción, revelación, publicación, emisión, desarrollo, fabricación y /o acción de marketing bajo cualquier manera y para cualquier propósito comercial o no comercial. Podremos, sin estar obligados a ello, monitorizar o revisar cualquier Comunicación de Usuario. No tendremos ninguna obligación de usar, devolver, revisar o responder a cualquier Comunicación del Usuario. No tendremos ninguna responsabilidad relacionada con el contenido de cualquier Comunicación de Usuario, tanto si está protegida o no por las leyes de copyright, difamación, privacidad, obscenidad u otras. Nos reservamos el derecho a retirar una o todas las Comunicaciones de Usuario que incluyan cualquier material considerado, por nosotros, como inadecuado o inaceptable.</p>
<p><b>Descargo de Responsabilidad:</b> www.bambini.club no se hace responsable de la veracidad, exactitud y calidad de la Web, sus servicios, información y materiales. Dichos servicios, información y materiales son presentados "tal cual" y son accesibles sin garantías de ninguna clase. www.bambini.club se reserva el derecho a interrumpir el acceso a la Web, así como la prestación de cualquiera o de todos los servicios que se prestan a través de la misma en cualquier momento y sin previo aviso, ya sea por motivos técnicos, de seguridad, de control, de mantenimiento, por fallos de suministro eléctrico o por cualquier otra causa justificada.</p>
<p>En consecuencia, www.bambini.club no garantiza la fiabilidad, la disponibilidad ni la continuidad de su web ni de los servicios, por lo que la utilización de los mismos por parte del usuario se lleva a cabo por su propia cuenta y riesgo, sin que, en ningún momento, puedan exigirse responsabilidades a www.bambini.club en este sentido.</p>
<p>BAMBINI.CLUB no asume ninguna responsabilidad ni será responsable por cualquier daño o cualquier virus que pueda infectar el sistema, equipo de telecomunicación y otra propiedad del Usuario que pueda ser causado o resultante del acceso, uso o exploración de esta Web o por la descarga de cualquier información o material de la misma.</p>
<p>En ningún caso, BAMBINI.CLUB ni cualquiera de sus Directores, funcionarios, empleados, accionistas, asociados, agentes, sucesores o cesionarios, ni ninguna parte implicada en la creación, producción o transmisión de esta Web serán responsables ante el Usuario o cualquier otra persona, por daños ocasionados, salvo casos de imprudencia grave o malintencionada originado por el uso, incapacidad para el uso o cualquier resultado del uso de esta Web, cualquier Web en link con ésta, o de los materiales, información o servicios contenidos en cualquier, una o todas las Web, tanto si los daños están basados en garantías, contactos, agravios o cualquier otra teoría legal, tanto si el Usuario está avisado o no sobre la posibilidad de tales daños. Las limitaciones sobre responsabilidad mencionadas anteriormente son aplicadas de acuerdo con la ley.</p>
<p><b>Comunicaciones:</b> A los efectos de las presentes Condiciones Generales, y para cualquier comunicación que sea precisa entre BAMBINI.CLUB y el Usuario, éste deberá dirigirse al Servicio de Atención al Cliente mediante llamada al teléfono <b>(664) 364 7961</b> o mediante al correo electrónico dirigido a <b>info@bambini.club</b>. Las comunicaciones de BAMBINI.CLUB al Usuario se realizarán conforme a los datos aportados por éste al registrarse en la Web. El Usuario acepta expresamente y para todas las comunicaciones relacionadas con la utilización la Web, y/o la contratación de los servicios en él ofertados, la utilización del correo electrónico como procedimiento válido para la remisión de dichas comunicaciones.</p>
<p><b>Garantía legal:</b> En caso de que el producto adquirido estuviera dañado o fuera defectuoso por causa no imputable al cliente, BAMBINI.CLUB procederá a la reparación, sustitución o devolución del importe, según proceda, durante los dos años siguientes a su fecha de adquisición.</p>
<p><b>Garantía comercial adicional del fabricante:</b> Además de la garantía legal de todos los productos de nuestra web, muchos de ellos cuentan con garantía comercial adicional del fabricante. Para obtener información adicional sobre la garantía del fabricante de un producto específico, ponte en contacto directamente con él.</p>
<p><b>Revisiones a estas Condiciones Generales:</b> Es posible que estas Condiciones Generales se modifiquen o incluyan cambios. Por esto, el usuario queda obligado a acceder a las presentes Condiciones Generales cada vez que acceda a la Web, asumiendo que les serán de aplicación las condiciones correspondientes que se encuentren vigentes en el momento de su acceso.</p>
<p><b>Jurisdicción y Tribunales:</b> Estas Condiciones Generales reemplazan cualquier acuerdo entre el Usuario y BAMBINI.CLUB, en tanto sea necesario resolver cualquier contradicción o ambigüedad entre ambos. Las presentes condiciones generales se regirán por lo aquí establecido y en su defecto por lo establecido en las Leyes mexicanas vigentes. Para cualquier controversia que pueda surgir en la interpretación o ejecución de las presentes Condiciones Generales, el usuario y BAMBINI.CLUB acuerdan someterse expresamente a los Juzgados y Tribunales que pudieran corresponder de conformidad con la legislación aplicable.</p>
<p><b>Terminación:</b> Tanto el Usuario como BAMBINI.CLUB pueden suspender o terminar una cuenta de usuario en esta Web en cualquier momento por cualquier razón. El Usuario es personalmente responsable por cualquier pedido realizado o por los cargos incurridos antes de terminar su cuenta en esta Web. Nos reservamos el derecho a cambiar, suspender o paralizar todos y cualquier aspecto de esta Web, en cualquier momento, sin previo aviso.</p>
<p><b>Asistencia Adicional:</b> Si no has comprendido alguna de las Condiciones Generales anteriores o si tienes alguna pregunta o comentario, te invitamos a que contactes con nuestro Servicio de Atención al Cliente mediante llamada al teléfono <b>(664) 364 7961</b> o mediante al correo electrónico dirigido a <b>info@bambini.club</b>.</p>
  </div>
</article>
  @endwhile
@endsection
